services:

  machinegun:
    environment: &otlp_enabled
      OTEL_TRACES_EXPORTER: otlp
      OTEL_TRACES_SAMPLER: parentbased_always_off
      OTEL_EXPORTER_OTLP_PROTOCOL: http_protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318

  testrunner:
    environment:
      <<: *otlp_enabled
      OTEL_SERVICE_NAME: shortener
      OTEL_TRACES_SAMPLER: parentbased_always_on
    depends_on:
      jaeger:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:1.60
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: "/go/bin/all-in-one-linux status"
      interval: 2s
      timeout: 1s
      retries: 20
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 5778:5778
      - 14250:14250
      - 16686:16686
