services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: $SERVICE_NAME
    working_dir: $PWD
    depends_on:
      postgres:
        condition: service_healthy
      machinegun:
        condition: service_healthy
    ports:
      - "8022:8022"
    command: /sbin/init

  machinegun:
    image: ghcr.io/valitydev/mg2:sha-436f723
    command: /opt/machinegun/bin/machinegun foreground
    volumes:
      - ./test/machinegun/config.yaml:/opt/machinegun/etc/config.yaml
      - ./test/machinegun/cookie:/opt/machinegun/etc/cookie
    healthcheck:
      test: "/opt/machinegun/bin/machinegun ping"
      interval: 5s
      timeout: 1s
      retries: 20

  postgres:
    image: postgres:15-bookworm
    command: -c 'max_connections=200'
    environment:
      POSTGRES_DB: "progressor_db"
      POSTGRES_USER: "progressor"
      POSTGRES_PASSWORD: "progressor"
      PGDATA: "/tmp/postgresql/data/pgdata"
    volumes:
      - progressor-data:/tmp/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U progressor -d progressor_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  progressor-data: